# Jekyll configuration for Open SDG platform
#
# You will need to change all of the capitalized variables below according
# to your Github setup. For example, if your site and data repositories are:
# -- https://github.com/my-awesome-github-org/my-awesome-site-repo
# -- https://github.com/my-awesome-github-org/my-awesome-data-repo
# Then you would want to make these replacements throughout this file:
# -- replace "my-github-org" with "my-awesome-github-org"
# -- replace "open-sdg-site-starter" with "my-awesome-site-repo"
# -- replace "open-sdg-data-starter" with "my-awesome-data-repo"

# Replace this title as needed.
title: Indicators For The Sustainable Development Goals
frontpage_heading: custom.frontpage_heading
# Replace the baseurl with the name of this repository.
baseurl: "/sdg-site-kazstat"
url: ""
data_dir: data
environment: staging
# Replace my-github-org and open-sdg-data-starter as needed.
remote_data_prefix: "https://kazstat.github.io/sdg-data-kazstat"
remote_translations:
  - https://open-sdg.github.io/sdg-translations/translations-0.6.0.json

analytics:
  ga_prod: ''

# Social media accounts.
#twitter: ''

facebook: 'statgov.kz'

# Replace the email addresses below.
email_contacts:
  questions: ai.dosanova@economy.gov.kz
  suggestions: as.abraeva@economy.gov.kz
  functional: ai.dosanova@economy.gov.kz

# Github Repo for Data
# Replace this value as needed.
repo_name: sdg-data-kazstat
branch: develop
# Replace this value as needed.
org_name: kazstat

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Kazakhstan
  adjective: Kazakh

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /guidance
    translation_key: menu.guidance
  - path: /faq
    translation_key: menu.faq

# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

# The list of languages that are translated. The first one is the default.
languages:
  - kz
  - ru
  - en
# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "kz"

# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: brockfanning/open-sdg@kazstat-launch

# Apply any custom CSS.
custom_css:
  - /assets/css/custom.css
# Apply any custom Javascript.
custom_js:
  - /assets/js/custom.js

create_goals:
  layout: goal-by-target-grid

create_indicators:
  layout: indicator

create_pages: true

# Mapping
map_options:
  tileURL: https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}
  tileOptions:
    id: mapbox.light
    accessToken: pk.eyJ1IjoiYnJvY2tmYW5uaW5nMSIsImEiOiJjaXplbmgzczgyMmRtMnZxbzlmbGJmdW9pIn0.LU-BYMX69uu3eGgk0Imibg
    attribution: <a href="https://www.mapbox.com">Mapbox</a> | <a href="https://leafletjs.com/">Leaflet</a>
  minZoom: 3
map_layers:
  - min_zoom: 3
    max_zoom: 10
    serviceUrl: https://kazstat.github.io/sdg-site-kazstat/assets/js/kazakhstan-regions.geojson
    nameProperty: kzName
    idProperty: kzCode
    staticBorders: false
